storage:
  default: 'local'
  qiniu:
    ak: ""
    sk: ""
    url: ""
    bucket: ""
app:
  jwtSecret: ""
  host: "http://127.0.0.1:8080"
server:
  address: ":8080"
  serverRoot: "storage"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
database:
  logger:
    path: "./storage/sql"
    level: "all"
    stdout: true
  default:
    type: "mysql"
    link: "root:d1ba0893@tcp(gr2d3539:3306)/Initialize?loc=Local&parseTime=true"
    debug: true
    charset: "utf8mb4"
redis:
  # 单实例配置示例1
  default:
    address: grcd99fc:6379
    pass:
    db: 1
logger:
  path:    "./storage/log"
  level:   "all"
  stdout:  true
grpc:
  open: false # 是否开启grpc服务
  logPath:          "./storage/grpc"
  logStdout:        true
  errorLogEnabled:  true
  accessLogEnabled: true
  errorStack:       true
etcd:
  host: "127.0.0.1:2379@root:123456"
websocket:
  logger:
    path: "./storage/sql"
    level: "all"
    stdout: false
langchain:
  open: true
  model: "qwen:0.5b"
